### ISSUE TITLE
Communication "stuck" after a few commands

### ISSUE THREAD

**Issue by oybed** [pfrommerd/insteon-terminal#14]
I am using the Insteon HUB (2245-222) and can successfully connect with `insteon-terminal` to perform commands. However, I often experience an issue where the same command cannot run twice or otherwise "stuck" - it seems to be in particular with commands that fetches the db content (either of the modem or the targeted device). If often errors out with the **did not get full database, giving up!** and any consecutive commands typically fails as well. I either have to `reload()` or kill/re-start the terminal and it works again. This issue seems to happen very frequent. 

Is this a known issue? Any configuration parameters I should try tweaking on my side? 

Please let me know what other information you may need from my side.

**Comment by berndpfrommer** [comment]
Yes, I have the same problem, and don't know how to fix it. I should learn how to debug python programs. Somehow an important thread is getting stuck or doesn't release a resource or something like that.
Maybe @pfrommerd has a clue?

**Comment by pfrommerd** [comment]
Hi, based on your description I can't seem to replicate your results. It might be related to the hub support--the hub I used to first implement hub support broke a year ago and so there's a chance something broke in the meanwhile.

You can change the log level with setLogLevel("TRACE") (you can configure the loggers more in resources/logback.xml and remove the ref="STDOUT" line if you want to disable printing to the console). The log file might give me a better idea of what's going on.

**Comment by oybed** [comment]
Thanks for the pointers. I did set the log level to TRACE, and I was able to capture a successful run of `getdb()`, followed by an unsuccessful one. Without digging in much, I don't know that it provides much additional info. Below is a snippet of the last "repeat" of the `MsgReader` - in case that provides any clues (maybe it's failing to parse the incoming message?)

BTW: the extra space and 2 at the beginning of the second line is how it shows in the trace ... newline character that's not handled(?)

```
20:55:02.953 [Thread-3] DEBUG us.pfrommer.insteon.msg.IOPort - Msg received: IN:Cmd:0x51|fromAddress:41.2A.F5|toAddress:39.B6.8E|messageFlags:0x11=DIRECT:1:0|command1:0x2F|command2:0x00|userData1:0x00|userData2:0x01|userData3:0x0F|userData4:0xF7|userData5:0x20|userData6:0xEA|userData7:0x01|userData8:0x39|userData9:0xB6|userData10:0x8E|userData11:0x03|userData12:0x1C|userData13:0x01|userData14:0x22|
 220:55:02.955 [Thread-3] TRACE us.pfrommer.insteon.msg.MsgReader - processing data: len 0 data:
20:55:02.956 [Thread-3] TRACE us.pfrommer.insteon.msg.MsgReader - msgLen expected: -1
20:55:02.956 [Thread-3] TRACE us.pfrommer.insteon.msg.MsgReader - keeping buffer len 0 data:
```

**Comment by pfrommerd** [comment]
I don't see anything immediately wrong with the log that you posted. The len 0 printout is a relatively common message when it has finished processing the message. I'm a bit swamped right now, but will try and figure out what's going as soon as I can get it to lock up in the manner you are describing.

**Comment by berndpfrommer** [comment]
OK, so I managed to get it to hang. Sometimes I can go for 1h+ without a single time, then it happens all the time. I ran a "jstack" on the hanging process, and here's the output. I don't know how to interpret it. Could be a problem inside python?

```
>>> 2018-01-20 21:09:55
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode):

"Thread-9" #39 prio=5 os_prio=0 tid=0x00007f6844783000 nid=0x6d7c in Object.wait() [0x00007f6821272000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x000000071ff4bc08> (a java.util.LinkedList)
        at java.lang.Object.wait(Object.java:502)
        at us.pfrommer.insteon.msg.IOPort$IOStreamWriter.run(Unknown Source)
        - locked <0x000000071ff4bc08> (a java.util.LinkedList)
        at java.lang.Thread.run(Thread.java:748)

"Thread-8" #38 prio=5 os_prio=0 tid=0x00007f6844661000 nid=0x6d7b runnable [0x00007f6821373000]
   java.lang.Thread.State: RUNNABLE
        at com.fazecast.jSerialComm.SerialPort.readBytes(Native Method)
        at com.fazecast.jSerialComm.SerialPort.access$700(SerialPort.java:47)
        at com.fazecast.jSerialComm.SerialPort$SerialPortInputStream.read(SerialPort.java:996)
        at us.pfrommer.insteon.msg.IOPort$IOStreamReader.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00007f68440c8000 nid=0x6ba7 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=0 tid=0x00007f68440c5800 nid=0x6ba6 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007f68440c3800 nid=0x6ba5 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f68440c1800 nid=0x6ba4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f68440bf000 nid=0x6ba3 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f68440bd800 nid=0x6ba2 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f684408a000 nid=0x6ba1 in Object.wait() [0x00007f68237f6000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000005cb224f90> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        - locked <0x00000005cb224f90> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f6844085000 nid=0x6ba0 in Object.wait() [0x00007f68238f7000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000005cb22c690> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        - locked <0x00000005cb22c690> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"MainThread" #1 prio=5 os_prio=0 tid=0x00007f6844007800 nid=0x6b96 runnable [0x00007f684ae76000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.read0(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:207)
        at jline.Terminal.readCharacter(Terminal.java:99)
        at jline.UnixTerminal.readVirtualKey(UnixTerminal.java:122)
        at jline.ConsoleReader.readVirtualKey(ConsoleReader.java:1606)
        at jline.ConsoleReader.readBinding(ConsoleReader.java:764)
        at jline.ConsoleReader.readLine(ConsoleReader.java:511)
        at jline.ConsoleReader.readLine(ConsoleReader.java:457)
        at us.pfrommer.insteon.terminal.console.terminal.JLineTerminal.readLine(Unknown Source)
        at us.pfrommer.insteon.terminal.InsteonTerminal.run(Unknown Source)
        at us.pfrommer.insteon.terminal.Main.main(Unknown Source)

"VM Thread" os_prio=0 tid=0x00007f684407d800 nid=0x6b9f runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f684401c800 nid=0x6b97 runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007f684401e800 nid=0x6b98 runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007f6844020000 nid=0x6b99 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007f6844022000 nid=0x6b9a runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007f6844023800 nid=0x6b9b runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007f6844025800 nid=0x6b9c runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007f6844027000 nid=0x6b9d runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007f6844029000 nid=0x6b9e runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007f68440cb000 nid=0x6ba8 waiting on condition 

JNI global references: 264

Heap
 PSYoungGen      total 237056K, used 227551K [0x0000000719100000, 0x000000072a100000, 0x00000007c0000000)
  eden space 231424K, 98% used [0x0000000719100000,0x0000000726f37c60,0x0000000727300000)
  from space 5632K, 0% used [0x0000000727900000,0x0000000727900000,0x0000000727e80000)
  to   space 23552K, 0% used [0x0000000728a00000,0x0000000728a00000,0x000000072a100000)
 ParOldGen       total 403968K, used 18808K [0x00000005cb200000, 0x00000005e3c80000, 0x0000000719100000)
  object space 403968K, 4% used [0x00000005cb200000,0x00000005cc45e178,0x00000005e3c80000)
 Metaspace       used 31941K, capacity 36232K, committed 36440K, reserved 1079296K
  class space    used 5624K, capacity 5925K, committed 6016K, reserved 1048576K


```
