### ISSUE TITLE
ubuntu 16

### ISSUE THREAD

**Issue by zirexix** [pfrommerd/insteon-terminal#20]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial

Connecting
Failed to initialize python interpreter: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./init.py", line 34, in <module>
    connectToMySerial()
  File "./init.py", line 28, in connectToMySerial
    connectToSerial("/dev/ttyUSB0")
  File "python/console_commands.py", line 93, in connectToSerial
    iofun.connectToSerial(dev)
  File "python/console_commands.py", line 93, in connectToSerial
    iofun.connectToSerial(dev)
  File "python/iofun.py", line 64, in connectToSerial
    console.connectToSerial(dev)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.fazecast.jSerialComm.SerialPort.<clinit>(SerialPort.java:181)
	at us.pfrommer.insteon.msg.serial.SerialIOStream.open(Unknown Source)
	at us.pfrommer.insteon.msg.IOPort.open(Unknown Source)
	at us.pfrommer.insteon.terminal.IOFun.updatePort(Unknown Source)
	at us.pfrommer.insteon.terminal.IOFun.connectToSerial(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: /tmp/1531246416517-libjSerialComm.so: /tmp/1531246416517-libjSerialComm.so: failed to map segment from shared object

**Comment by pfrommerd** [comment]
That's unusual, what platform are you running on? (arm, amd64, etc)

**Comment by zirexix** [comment]
uname -a
Linux 4.9.0-040900-generic #201612111631 SMP Sun Dec 11 21:33:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux, version is at the top of first post.

Very unusual, I could not make it run in a decent amount of time I would allocate for such problem.

I just wanted to see if the terminal works, on UserData2 on a thermostat, because on a implementation I work, based on the 'Developer Notes, Insteon Thermostat (If I can call it notes, and .. who wrote it never mind, completely mess' I cannot read the  date-time.
